version: "3"

services:
  client:
    build: ./client
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app/client
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: your_postgres_username
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_database_name
    depends_on:
      - db
    volumes:
      - ./server:/server
