version: "3"

services:
  client:
    build: ./client
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app/client
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
