version: 2.1 # Update pipeline version to 2.1

orbs:
  node: circleci/node@4.0.0 # Update to the latest version of the node orb

jobs:
  build_client:
    docker:
      - image: circleci/node:16-browsers # Update to Node.js 16.x with browsers support
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm run client:install
      - run:
          name: Build Angular app
          command: npm run client:build

  build_server:
    docker:
      - image: circleci/node:16 # Update to Node.js 16.x
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm run server:install
      - run:
          name: Run linting
          command: npm run server:lint
      - run:
          name: Build NestJS app
          command: npm run server:build

  build-push-docker-image:
    docker:
      - image: docker/compose:1.29.2

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching:
            true

            # echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build and push Docker image
          command: |
            docker-compose build
            echo "${DOCKER_ACCESS_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker-compose push

workflows:
  build_and_deploy:
    jobs:
      # - build_client
      # - build_server
      - build-push-docker-image
        # requires:
        #   - build_client
        #   - build_server
